public enum TileID
{
    TILE,
    HIDDEN_TILE,
    COIN,
    START_POINT,
    VM_POINT,

    GIMIC_CUSTOM = 1000,
    
    PRESSURE_TOGGLE = 1010,
    PRESSURE_ONCE,
    PRESSURE_KEEP,
    PRESSURE_BOX,
    
    LEVER_TOGGLE = 1020,
    LEVER_ONCE,
    
    DOOR_TOGGLE = 1030,
    DOOR_ONSTART,
    
    PLATFORM_TOGGLE = 1040,
    PLATFORM_ONSTART,
    PLATFORM_POINT,
    
    TRAMPOLINE = 1050,
    TRAMPOLINE_POINT,
    
    BOX = 1060,
    
    PIT = 1070,
}